# Reproducibility
seed: 0

# WandB
wandb:
  wandb_run_id: null
  wandb_run_name: fold_0
  wandb_project_name: nnUNetRegression
  logs_path: /home/gridsan/nchutisilp/datasets/nnUNetRegression/logs # SuperCloud
  # logs_path: logs # Bizon

# Data
data:
  fold: 0 # should change when doing different folds
  tabular_data_directory: /home/gridsan/nchutisilp/projects/ModelsGenesis/notebooks/tabular_data # SuperCloud
  data_directory: /home/gridsan/nchutisilp/datasets/Unlabeled_OCT_by_CADx/NiFTI/ # SuperCloud
  # data_directory: /storage_bizon/naravich/Unlabeled_OCT_by_CADx/NiFTI/ # Bizon
  # patch_size: [512, 512, 384]
  patch_size: [256, 256, 384]
  queue_max_length: 16
  samples_per_volume: 4
  num_workers: 5
  batch_size: 2
  num_classes: 1
  input_modality: pre
  output_modality: post
  output_metrics: [MCS_MSCT]
  nan_handling: drop
  target_normalization: minmax
  overfit: true

# Train
train:
  max_epochs: 10000
  patience: 1000

# Pre-trained
# pre_trained_weight_path: /home/gridsan/nchutisilp/datasets/ModelGenesisOutputs/ModelGenesisNNUNetPretrainingV2_noNorm/Genesis_OCT_Best.pt # SuperCloud
pre_trained_weight_path: null
# pre_trained_weight_path: /storage_bizon/naravich/ModelGenesisNNUNetPretrainingV2_noNorm/Genesis_OCT_Best.pt # Bizon

# Model
model:
  freeze_encoder: False
  head:
    task: regression
    in_channels: 320
    pooling: avg
    dropout: 0


# Optimizer
optimizer:
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 0.0
  nesterov: False
  scheduler_step_size: 60
  scheduler_gamma: 0.5

# nnUNet architecutre
nnUNet:
  dataset_name_or_id: "301"
  configuration: 3d_fullres
  trainer_name: nnUNetTrainer
  plans_identifier: nnUNetPlans
  fold: 0 # any fold would do