# Reproducibility
seed: 42

# WandB
wandb:
  wandb_run_id: null
  wandb_run_name: null
  wandb_project_name: GenesisFinetuneTest
  logs_path: /home/gridsan/nchutisilp/datasets/ModelGenesisOutputs/ModelGenesisNNUNetFinetuningV2_noNorm/LogsBCEAug

# Data
data:
  fold: 0 # should change when doing different folds
  data_directory: /home/gridsan/nchutisilp/datasets/nnUNet_Datasets/nnUNet_raw/Dataset303_Calcium_OCTv2/
  patch_size: [128, 128, 64]
  queue_max_length: 1000
  samples_per_volume: 100
  num_workers: 39
  batch_size: 16

# Train
train:
  max_epochs: 1000
  patience: 50

# Pre-trained
pre_trained_weight_path: /home/gridsan/nchutisilp/datasets/ModelGenesisOutputs/ModelGenesisNNUNetPretrainingV2_noNorm/Genesis_OCT_Best.pt

# Optimizer
optimizer:
  learning_rate: 1
  scheduler_step_size: 30
  scheduler_gamma: 0.5

# nnUNet architecutre
nnUNet:
  dataset_name_or_id: "301"
  configuration: 3d_fullres
  trainer_name: nnUNetTrainer
  plans_identifier: nnUNetPlans
  fold: 0 # any fold would do